'use strict';

/**
 * Bundled offline mock of the Arena Agent API.
 *
 * It speaks OpenAI-compatible /v1/chat/completions (streaming + non-streaming)
 * and drives a small scripted "brain" that demonstrates the full agent loop:
 * plan → create files → verify with a shell command → mark plan done → summary.
 *
 * Used by `arena --mock`, the demo script and the e2e smoke test.
 */

const http = require('http');

const AUTH_FILE = 'src/auth.js';
const AUTH_TEST_CMD = `node -e "const a=require('./src/auth'); const t=a.register('kai','s3cret'); const ok=a.verify(t); console.log('auth check:', ok ? 'PASS' : 'FAIL');"`;

const AUTH_MODULE = `'use strict';

const crypto = require('crypto');

// Minimal in-memory auth module generated by Arena Agent (mock demo).
const users = new Map();   // username -> { salt, hash }
const tokens = new Map();  // token -> username

function hash(password, salt) {
  return crypto.scryptSync(password, salt, 32).toString('hex');
}

function register(username, password) {
  if (!username || !password) throw new Error('username and password are required');
  if (users.has(username)) throw new Error('user already exists: ' + username);
  const salt = crypto.randomBytes(16).toString('hex');
  users.set(username, { salt, hash: hash(password, salt) });
  return issueToken(username);
}

function login(username, password) {
  const u = users.get(username);
  if (!u) return null;
  if (hash(password, u.salt) !== u.hash) return null;
  return issueToken(username);
}

function issueToken(username) {
  const token = crypto.randomBytes(24).toString('base64url');
  tokens.set(token, username);
  return token;
}

function verify(token) {
  return tokens.has(token) ? { username: tokens.get(token) } : null;
}

function logout(token) {
  return tokens.delete(token);
}

module.exports = { register, login, verify, logout };
`;

function taskEcho(messages) {
  const lastUser = [...messages].reverse().find((m) => m.role === 'user' && typeof m.content === 'string');
  return lastUser ? String(lastUser.content).slice(0, 120).replace(/\n/g, ' ') : '(no task)';
}

function pickResponse(messages) {
  const step = messages.filter((m) => m.role === 'tool').length;
  const task = taskEcho(messages);

  switch (step) {
    case 0:
      return {
        tool_calls: [
          {
            id: 'mock_call_plan',
            type: 'function',
            function: {
              name: 'update_plan',
              arguments: JSON.stringify({
                todos: [
                  { content: `Understand task: ${task}`, status: 'done' },
                  { content: 'Implement auth module (src/auth.js)', status: 'in_progress' },
                  { content: 'Verify with a smoke test', status: 'pending' },
                ],
              }),
            },
          },
        ],
      };
    case 1:
      return {
        tool_calls: [
          {
            id: 'mock_call_write',
            type: 'function',
            function: {
              name: 'write_file',
              arguments: JSON.stringify({ path: AUTH_FILE, content: AUTH_MODULE }),
            },
          },
        ],
      };
    case 2:
      return {
        tool_calls: [
          {
            id: 'mock_call_run',
            type: 'function',
            function: {
              name: 'run_command',
              arguments: JSON.stringify({ command: AUTH_TEST_CMD, description: 'smoke-test the auth module' }),
            },
          },
        ],
      };
    case 3:
      return {
        tool_calls: [
          {
            id: 'mock_call_plan2',
            type: 'function',
            function: {
              name: 'update_plan',
              arguments: JSON.stringify({
                todos: [
                  { content: `Understand task: ${task}`, status: 'done' },
                  { content: 'Implement auth module (src/auth.js)', status: 'done' },
                  { content: 'Verify with a smoke test', status: 'done' },
                ],
              }),
            },
          },
        ],
      };
    default:
      return {
        content:
          `Done. I added a small authentication module for the task: "${task}".\n\n` +
          'What changed:\n' +
          `- Created ${AUTH_FILE} with register/login/verify/logout backed by crypto.scrypt password hashing and opaque session tokens.\n\n` +
          'Verification:\n' +
          '- Ran a smoke test that registers a user, verifies the issued token, and printed `auth check: PASS`.\n\n' +
          'Next steps you may want: wire the module into your HTTP routes, add persistent storage, and add real tests. (Note: this reply came from the bundled offline mock — point ARENA_BASE_URL/Arena_API_KEY at the real Arena Agent API for full intelligence.)',
      };
  }
}

/* ------------------------------------------------------------------ */

function messageToEvents(msg) {
  const events = [];
  events.push({ choices: [{ index: 0, delta: { role: 'assistant' }, finish_reason: null }] });

  if (msg.content) {
    const pieces = [];
    for (let i = 0; i < msg.content.length; i += 14) pieces.push(msg.content.slice(i, i + 14));
    for (const p of pieces) events.push({ choices: [{ index: 0, delta: { content: p }, finish_reason: null }] });
    events.push({ choices: [{ index: 0, delta: {}, finish_reason: 'stop' }] });
  }

  if (msg.tool_calls && msg.tool_calls.length) {
    msg.tool_calls.forEach((tc, i) => {
      events.push({
        choices: [
          {
            index: 0,
            delta: { tool_calls: [{ index: i, id: tc.id, type: 'function', function: { name: tc.function.name, arguments: '' } }] },
            finish_reason: null,
          },
        ],
      });
      const args = tc.function.arguments;
      for (let j = 0; j < args.length; j += 48) {
        events.push({
          choices: [
            { index: 0, delta: { tool_calls: [{ index: i, function: { arguments: args.slice(j, j + 48) } }] }, finish_reason: null },
          ],
        });
      }
    });
    events.push({ choices: [{ index: 0, delta: {}, finish_reason: 'tool_calls' }] });
  }

  events.push({ usage: { prompt_tokens: 1200, completion_tokens: 90, total_tokens: 1290 } });
  return events;
}

function startMockServer(port = 0) {
  const server = http.createServer((req, res) => {
    if (req.method === 'GET' && req.url === '/v1/models') {
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ data: [{ id: 'arena-agent' }, { id: 'arena-agent-fast' }, { id: 'arena-agent-mini' }] }));
      return;
    }
    if (req.method === 'POST' && req.url === '/v1/chat/completions') {
      let body = '';
      req.on('data', (d) => (body += d));
      req.on('end', () => {
        let parsed;
        try {
          parsed = JSON.parse(body || '{}');
        } catch {
          res.writeHead(400, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ error: { message: 'bad JSON' } }));
          return;
        }
        const msg = pickResponse(parsed.messages || []);
        if (!parsed.stream) {
          res.writeHead(200, { 'content-type': 'application/json' });
          res.end(
            JSON.stringify({
              id: 'mock-' + Date.now(),
              choices: [{ index: 0, message: { role: 'assistant', ...msg }, finish_reason: msg.tool_calls ? 'tool_calls' : 'stop' }],
              usage: { prompt_tokens: 1200, completion_tokens: 90, total_tokens: 1290 },
            })
          );
          return;
        }
        res.writeHead(200, { 'content-type': 'text/event-stream', 'cache-control': 'no-cache' });
        const events = messageToEvents(msg);
        let i = 0;
        const timer = setInterval(() => {
          if (i >= events.length) {
            res.write('data: [DONE]\n\n');
            clearInterval(timer);
            res.end();
            return;
          }
          res.write(`data: ${JSON.stringify(events[i++])}\n\n`);
        }, 8);
      });
      return;
    }
    res.writeHead(404, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ error: { message: 'not found' } }));
  });

  return new Promise((resolve, reject) => {
    server.on('error', reject);
    server.listen(port, '127.0.0.1', () => {
      resolve({
        port: server.address().port,
        url: `http://127.0.0.1:${server.address().port}`,
        close: () => new Promise((r) => server.close(r)),
      });
    });
  });
}

module.exports = { startMockServer };

if (require.main === module) {
  const port = Number(process.argv[2] || 8420);
  startMockServer(port).then((s) => {
    console.log(`mock Arena Agent API on ${s.url}/v1`);
  });
}
